# Generated by Django 4.2.2 on 2023-06-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=250)),
                ('DOB', models.DateField()),
                ('AGE', models.IntegerField()),
                ('EMAIL_ID', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.IntegerField()),
                ('GENDER', models.CharField(max_length=250)),
                ('ADDRESS', models.TextField()),
                ('DISTRICT', models.CharField(max_length=250)),
                ('BRANCHES', models.CharField(max_length=250)),
                ('ACCOUNT_TYPE', models.CharField(max_length=250)),
                ('MATERIALS_PROVIDE', models.CharField(max_length=250)),
            ],
        ),
    ]
